### ISSUE TITLE
[BUG] [Crunchy] Unable to download season without name

### ISSUE THREAD

**Issue by Jaynator495** [anidl/multi-downloader-nx#190]
** Main info: **
Oreimo Season 1 cannot download - I suspect it's because it doesn't have season name, but have no evidence to suggest this.

Script version: 2.0.9
Service: Crunchy
Show ID: GYQ4WX036 
Episode ID: ?
Command used: node .\index.js --service crunchy --srz GYQ4WX036 --all

Console output: 
```text
=== Multi Downloader NX 2.0.9 ===

[INFO] USER: Jaynator495
[INFO] Your Country: US

  [Z:GYQ4WX036] Oreimo (Seasons: 2, EPs: 25) [SUB]
  [S:GY5VP833Y] NO_TITLE (Season: 1) [SUB]
  [S:GR09X82ER] Oreimo Season 2 (Season: 2) [SUB]
[1] Oreimo Season 2 - My Little Sister Can't Come Back Home Again [Japanese]
[2] Oreimo Season 2 - The Onii-san I Trusted and Sent Off Can't Get This Hooked on Portable Bishoujo Games and Start Sexually Harassing Me [Japanese]
[3] Oreimo Season 2 - My Friend Can't Take Off Her Glasses [Japanese]
[4] Oreimo Season 2 - My Little Sister's Rival Can't Come to Japan [Japanese]
[5] Oreimo Season 2 - I Can't Be My Little Sister's Boyfriend, and My Little Sister Can't Have a Boyfriend [Japanese]
[6] Oreimo Season 2 - My Little Sister Can't Be Bringing Her Boyfriend Home [Japanese]
[7] Oreimo Season 2 - I Can't Become a Couple with My Underclassman [Japanese]
[8] Oreimo Season 2 - I Can't Create a Summer Memory with My Underclassman [Japanese]
[9] Oreimo Season 2 - My Little Sister Can't Be This Cute! [Japanese]
[10] Oreimo Season 2 - My Little Sister Can't Wear a Wedding Dress [Japanese]
[11] Oreimo Season 2 - Little Sisters Can't Barge In On Their Brother Who Lives Alone [Japanese][12] Oreimo Season 2 - Total Angel Ayase-tan Can't Descend Upon My Place While I Live Alone [Japanese]
[13] Oreimo Season 2 - Little Sisters Can't Fall in Love With Their Older Brothers! [Japanese]  

------------------------------

[1] - My Little Sister Can't Come Back Home Again [✓ Japanese]
[2] - The Onii-san I Trusted and Sent Off Can't Get This Hooked on Portable Bishoujo Games and Start Sexually Harassing Me [✓ Japanese]
[3] - My Friend Can't Take Off Her Glasses [✓ Japanese]
[4] - My Little Sister's Rival Can't Come to Japan [✓ Japanese]
[5] - I Can't Be My Little Sister's Boyfriend, and My Little Sister Can't Have a Boyfriend [✓ Japanese]
[6] - My Little Sister Can't Be Bringing Her Boyfriend Home [✓ Japanese]
[7] - I Can't Become a Couple with My Underclassman [✓ Japanese]
[8] - I Can't Create a Summer Memory with My Underclassman [✓ Japanese]
[9] - My Little Sister Can't Be This Cute! [✓ Japanese]
[10] - My Little Sister Can't Wear a Wedding Dress [✓ Japanese]
[11] - Little Sisters Can't Barge In On Their Brother Who Lives Alone [✓ Japanese]
[12] - Total Angel Ayase-tan Can't Descend Upon My Place While I Live Alone [✓ Japanese]
[13] - Little Sisters Can't Fall in Love With Their Older Brothers! [✓ Japanese]
[INFO] Requesting: [GYE5X370R] Oreimo Season 2 - 1 - My Little Sister Can't Come Back Home Again
```

** Additional Info: **

**Comment by izu-co** [comment]
Can you give me the full output until the program terminates, please?

**Comment by Jaynator495** [comment]
Unfortunately not really. It just proceeds to download all of season 2 but ignore all of season 1. 
I can't share anymore than that because powershell has a line limit, but pretty much after that it just normally downloads all of season 2 and stops after finishing season 2

**Comment by izu-co** [comment]
I will look into it

**Comment by izu-co** [comment]
I confirmed that it is indeed a bug and I work on it

**Comment by izu-co** [comment]
Found the issue. The multi downloading is currently not able to handle multiple different season.
The fix will take a while - sorry about that

**Comment by izu-co** [comment]
I just released a fix.
Can you try it for me to confirm that it is working for you? 

Sorry for the wait btw

**Comment by Jaynator495** [comment]
While it did do a lot better than it did before, it is still not working, not sure what is different about this season from other crunchy seasons but... It finds all the episodes of season 1 now, but can't find any url to download them, so it ends up skipping straight to season 2
```text
=== Multi Downloader NX 2.0.11 ===

[INFO] USER: Jaynator495
[INFO] Your Country: US

  [Z:GYQ4WX036] Oreimo (Seasons: 2, EPs: 25) [SUB]
  [S:GY5VP833Y] NO_TITLE (Season: 1) [SUB]
  [S:GR09X82ER] Oreimo Season 2 (Season: 2) [SUB]
[S1E1]  - My Little Sister Can't Be My Love [Japanese]
[S1E2]  - My Little Sister Can't Bring Me to an IRL Meet [Japanese]
[S1E3]  - My Little Sister Can't Be This Cute [Japanese]
[S1E4]  - My Little Sister Can't be Going to Summerket [Japanese]
[S1E5]  - My Little Sister's Best Friend Can't Be This XX [Japanese]
[S1E6]  - My Childhood Friend Can't Be This Cute [Japanese]
[S1E7]  - My Little Sister Can't Be A Novelist [Japanese]
[S1E8]  - My Little Sister Can't Be Animated [Japanese]
[S1E9]  - My Little Sister Can't Be This Absorbed into Eroge [Japanese]
[S1E10]  - My Little Sister Can't Be Cosplaying Like This [Japanese]
[S1E11]  - My Little Sister Can't Be This Maid [Japanese]
[S1E12]  - My Little Sister's Advice Can't End Here (GOOD END) [Japanese]
[S2E1] Oreimo Season 2 - My Little Sister Can't Come Back Home Again [Japanese]
[S2E2] Oreimo Season 2 - The Onii-san I Trusted and Sent Off Can't Get This Hooked on Portable Bishoujo Games and Start Sexually Harassing Me [Japanese]
[S2E3] Oreimo Season 2 - My Friend Can't Take Off Her Glasses [Japanese]
[S2E4] Oreimo Season 2 - My Little Sister's Rival Can't Come to Japan [Japanese]
[S2E5] Oreimo Season 2 - I Can't Be My Little Sister's Boyfriend, and My Little Sister Can't Have 
a Boyfriend [Japanese]
[S2E6] Oreimo Season 2 - My Little Sister Can't Be Bringing Her Boyfriend Home [Japanese]
[S2E7] Oreimo Season 2 - I Can't Become a Couple with My Underclassman [Japanese]
[S2E8] Oreimo Season 2 - I Can't Create a Summer Memory with My Underclassman [Japanese]
[S2E9] Oreimo Season 2 - My Little Sister Can't Be This Cute! [Japanese]
[S2E10] Oreimo Season 2 - My Little Sister Can't Wear a Wedding Dress [Japanese]
[S2E11] Oreimo Season 2 - Little Sisters Can't Barge In On Their Brother Who Lives Alone [Japanese]
[S2E12] Oreimo Season 2 - Total Angel Ayase-tan Can't Descend Upon My Place While I Live Alone [Japanese]
[S2E13] Oreimo Season 2 - Little Sisters Can't Fall in Love With Their Older Brothers! [Japanese] 

------------------------------

[S1E1] - My Little Sister Can't Be My Love [✓ Japanese]
[S1E2] - My Little Sister Can't Bring Me to an IRL Meet [✓ Japanese]
[S1E3] - My Little Sister Can't Be This Cute [✓ Japanese]
[S1E4] - My Little Sister Can't be Going to Summerket [✓ Japanese]
[S1E5] - My Little Sister's Best Friend Can't Be This XX [✓ Japanese]
[S1E6] - My Childhood Friend Can't Be This Cute [✓ Japanese]
[S1E7] - My Little Sister Can't Be A Novelist [✓ Japanese]
[S1E8] - My Little Sister Can't Be Animated [✓ Japanese]
[S1E9] - My Little Sister Can't Be This Absorbed into Eroge [✓ Japanese]
[S1E10] - My Little Sister Can't Be Cosplaying Like This [✓ Japanese]
[S1E11] - My Little Sister Can't Be This Maid [✓ Japanese]
[S1E12] - My Little Sister's Advice Can't End Here (GOOD END) [✓ Japanese]
[S2E1] - My Little Sister Can't Come Back Home Again [✓ Japanese]
[S2E2] - The Onii-san I Trusted and Sent Off Can't Get This Hooked on Portable Bishoujo Games and 
Start Sexually Harassing Me [✓ Japanese]
[S2E3] - My Friend Can't Take Off Her Glasses [✓ Japanese]
[S2E4] - My Little Sister's Rival Can't Come to Japan [✓ Japanese]
[S2E5] - I Can't Be My Little Sister's Boyfriend, and My Little Sister Can't Have a Boyfriend [✓ Japanese]
[S2E6] - My Little Sister Can't Be Bringing Her Boyfriend Home [✓ Japanese]
[S2E7] - I Can't Become a Couple with My Underclassman [✓ Japanese]
[S2E8] - I Can't Create a Summer Memory with My Underclassman [✓ Japanese]
[S2E9] - My Little Sister Can't Be This Cute! [✓ Japanese]
[S2E10] - My Little Sister Can't Wear a Wedding Dress [✓ Japanese]
[S2E11] - Little Sisters Can't Barge In On Their Brother Who Lives Alone [✓ Japanese]
[S2E12] - Total Angel Ayase-tan Can't Descend Upon My Place While I Live Alone [✓ Japanese]       
[S2E13] - Little Sisters Can't Fall in Love With Their Older Brothers! [✓ Japanese]
[INFO] Requesting: [GRWE4P1QR] Oreimo - 1 - My Little Sister Can't Be My Love
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [G609X83E6] Oreimo - 2 - My Little Sister Can't Bring Me to an IRL Meet        
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [G67598QJR] Oreimo - 3 - My Little Sister Can't Be This Cute
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GYX0JZQKR] Oreimo - 4 - My Little Sister Can't be Going to Summerket
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GR19X8326] Oreimo - 5 - My Little Sister's Best Friend Can't Be This XX       
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GYNQVE20Y] Oreimo - 6 - My Childhood Friend Can't Be This Cute
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [G6MGE02G6] Oreimo - 7 - My Little Sister Can't Be A Novelist
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [G63VK8ZWY] Oreimo - 8 - My Little Sister Can't Be Animated
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GR2P4Z2ER] Oreimo - 9 - My Little Sister Can't Be This Absorbed into Eroge    
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GRZXJPG9Y] Oreimo - 10 - My Little Sister Can't Be Cosplaying Like This       
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [G6Q4WX23R] Oreimo - 11 - My Little Sister Can't Be This Maid
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GYWE4PQQY] Oreimo - 12 - My Little Sister's Advice Can't End Here (GOOD END)  
[WARN] Raw streams not available!
[WARN] Try hardsubs stream: en
[INFO] Selecting raw stream
[WARN] Can't find urls for subtitles!
[INFO] Skip muxing since no vids are downloaded
[INFO] Requesting: [GYE5X370R] Oreimo Season 2 - 1 - My Little Sister Can't Come Back Home Again  
[INFO] Selecting raw stream
[INFO] Full stream found! (✓1: adaptive_hls/jpn/- )
[INFO] Full stream found! ( 2: download_hls/jpn/- )
[INFO] Full stream found! ( 3: vo_adaptive_hls/jpn/- )
```

**Comment by izu-co** [comment]
That’s because they don’t have soft subs.
You would need to`—hlsubs en`

**Comment by Jaynator495** [comment]
Thanks, using --hslang worked (hlsubs isn't in the flags list?)
That fixes that problem, however I do have another problem, going to open another issue for that
